name: Test Build CSVGenerator

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout Common library
      uses: actions/checkout@v4
      with:
        repository: DarkPhilosophy/Common
        path: Common
        ref: test
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y
      shell: pwsh
      
    - name: List directory structure
      run: |
        Write-Output "Current directory: $(Get-Location)"
        Write-Output "Directory structure:"
        Get-ChildItem -Path . -Recurse -Depth 2 | Select-Object FullName
        Write-Output "Project files:"
        Get-ChildItem -Path . -Include *.csproj -Recurse | Select-Object FullName
      shell: pwsh
      
    - name: Update target frameworks in project files
      run: |
        Get-ChildItem -Path . -Include *.csproj -Recurse | ForEach-Object {
          $content = Get-Content $_.FullName -Raw
          $updatedContent = $content -replace '<TargetFrameworks>net48;net5.0-windows;net7.0-windows;net10.0-windows</TargetFrameworks>', '<TargetFrameworks>net48</TargetFrameworks>'
          $updatedContent = $updatedContent -replace '<TargetFramework>net10.0-windows</TargetFramework>', '<TargetFramework>net48</TargetFramework>'
          Set-Content -Path $_.FullName -Value $updatedContent
          Write-Output "Updated target framework in $($_.FullName)"
        }
      shell: pwsh
      
    - name: Restore NuGet packages
      run: |
        nuget restore CSVGenerator.csproj
      shell: pwsh
      
    - name: Build
      run: |
        msbuild CSVGenerator.csproj /p:Configuration=Release /p:Platform="Any CPU" /verbosity:detailed
      shell: pwsh
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CSVGenerator-net48
        path: bin/Release/net48
        if-no-files-found: warn
