name: Test Build and Release CSVGenerator

on:
  push:
    branches: [ test ] 
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build-release: 
    runs-on: windows-latest
    
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout CSVGenerator (this repository)
      uses: actions/checkout@v4
      with:
        path: CSVGenerator
        fetch-depth: 0 

    - name: Checkout Common library
      uses: actions/checkout@v4
      with:
        repository: DarkPhilosophy/Common
        path: Common
        ref: test

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
        
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y --no-progress
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Choco install failed for netfx-4.8-devpack"
          exit 1
        }

    - name: Temporarily update TargetFrameworks in project files for CI
      env:
        CI_WORKSPACE: ${{ github.workspace }} 
      run: |
        # (TFM update script - assumed to be the last working version)
        Write-Output "Script starting. Value of CI_WORKSPACE from step env: '$($env:CI_WORKSPACE)'"
        Write-Output "Script starting. Value of GITHUB_WORKSPACE from direct env access: '$($env:GITHUB_WORKSPACE)'"
        $baseWorkspacePath = $env:GITHUB_WORKSPACE
        if ([string]::IsNullOrWhiteSpace($baseWorkspacePath)) {
            $baseWorkspacePath = $env:CI_WORKSPACE
        }
        if ([string]::IsNullOrWhiteSpace($baseWorkspacePath)) {
            Write-Error "Base workspace path is empty or null. Aborting."
            exit 1
        }
        $csvGeneratorCheckoutPath = Join-Path $baseWorkspacePath "CSVGenerator" 
        $commonCheckoutPath = Join-Path $baseWorkspacePath "Common"          
        $projectRoots = @( $csvGeneratorCheckoutPath, $commonCheckoutPath )
        $tfmToReplace = 'net10.0-windows'; $tfmReplacement = 'net9.0-windows'
        $escapedTfmToReplace = [regex]::Escape($tfmToReplace)
        foreach ($rootPath in $projectRoots) {
            if (Test-Path $rootPath) {
                Get-ChildItem -Path $rootPath -Include *.csproj -Recurse | ForEach-Object {
                    $projectFile = $_.FullName; 
                    $content = Get-Content $projectFile -Raw; $originalContent = $content; $wasModified = $false
                    if ($content.Contains($tfmToReplace)) {
                        $content = $content.Replace($tfmToReplace, $tfmReplacement)
                        if ($content -ne $originalContent) { $wasModified = $true }
                    }
                    if (-not $wasModified -and $content.Contains($tfmToReplace)) {
                        $regexPatternForTargetFrameworks = "([<TargetFrameworks>].*?;?)\s*$($escapedTfmToReplace)\s*(;?.*?<\TargetFrameworks>)"
                        if ($content -match "<TargetFrameworks>.*$($escapedTfmToReplace).*</TargetFrameworks>") {
                            $tempContent = $content -replace $regexPatternForTargetFrameworks, ('$1' + $tfmReplacement + '$3')
                            if ($tempContent -ne $content) { $content = $tempContent; $wasModified = $true;}
                        }
                        if (-not $wasModified -and $content -match "<TargetFramework>$($escapedTfmToReplace)</TargetFramework>") {
                             $regexPatternForTargetFramework = "<TargetFramework>$($escapedTfmToReplace)</TargetFramework>"
                             $replacementForTf = "<TargetFramework>$($tfmReplacement)</TargetFramework>"
                             $tempContent = $content -replace $regexPatternForTargetFramework, $replacementForTf
                             if ($tempContent -ne $content) { $content = $tempContent; $wasModified = $true;}
                        }
                    }
                    if ($wasModified) { Set-Content -Path $projectFile -Value $content -Force -Encoding UTF8; Write-Output "Updated $projectFile."}
                }
            }
        }

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-tfmfix-${{ hashFiles('**/csproj') }}-${{ github.run_id }} 
        restore-keys: |
          ${{ runner.os }}-nuget-tfmfix-${{ hashFiles('**/csproj') }}-
          ${{ runner.os }}-nuget-tfmfix-
          ${{ runner.os }}-nuget-
      
    - name: Build Common library for net48
      run: dotnet build (Join-Path $env:GITHUB_WORKSPACE "Common" "Common.csproj") -c Release -f net48

    - name: Publish CSVGenerator for net48
      id: publish-csvgenerator 
      run: |
        $publishDir = Join-Path $env:GITHUB_WORKSPACE "publish_output" "net48_win-x64"
        dotnet publish (Join-Path $env:GITHUB_WORKSPACE "CSVGenerator" "CSVGenerator.csproj") `
          -r win-x64 `
          -f net48 `
          -c Release `
          -o $publishDir
        Write-Output "CSVGenerator published to $publishDir"
        echo "publish_dir=$publishDir" >> $env:GITHUB_OUTPUT
        
    - name: Prepare Release Assets and Metadata (Highly Simplified)
      id: release-prep 
      run: |
        $ErrorActionPreference = "Stop" 
        try {
            $publishDir = "${{ steps.publish-csvgenerator.outputs.publish_dir }}"
            Write-Output "INFO: Publish directory for asset prep: $publishDir"
            $stagingDir = Join-Path $env:GITHUB_WORKSPACE "release_staging"
            New-Item -ItemType Directory -Path $stagingDir -Force
            Write-Output "INFO: Staging directory ensured: $stagingDir"
            
            $exeFile = Get-ChildItem -Path $publishDir -Filter CSVGenerator.exe -ErrorAction SilentlyContinue | Select-Object -First 1
            
            if ($exeFile) {
                Write-Output "INFO: Found executable: $($exeFile.FullName)"
                # Minimal data for now
                $fileVersion = "0.0.0.0-test"
                $commitHash = "test-commit"
                $rawCommitMessage = "Test Commit Message"
                $sha256 = "test-sha256"
                $buildTime = "test-buildtime"

                Write-Output "TEST POINT 1: Simple assignments done."

                # Test line 1 for release notes (previously problematic area)
                $_test_line1 = "- **Commit:** `$($commitHash)`"
                Write-Output "TEST POINT 2: _test_line1 assignment successful: $_test_line1"

                # Test line 2 for release notes (previously problematic area)
                $_test_line2 = "- **Message:**"
                Write-Output "TEST POINT 3: _test_line2 assignment successful: $_test_line2"

                $defaultReleaseNotesBody = $_test_line1 + [Environment]::NewLine + $_test_line2 + [Environment]::NewLine + "  > " + $rawCommitMessage
                Write-Output "TEST POINT 4: defaultReleaseNotesBody assignment successful."
                
                $releaseNotesBody = $defaultReleaseNotesBody

                # --- Minimal Metadata ---
                $metadataContent = "Version: $fileVersion`nCommit: $commitHash`nSHA256: $sha256"
                $metadataFilePath = Join-Path $stagingDir "$($exeFile.Name).metadata.txt" # Assumes exeFile.Name is valid
                Set-Content -Path $metadataFilePath -Value $metadataContent
                Write-Output "INFO: Minimal metadata written."

                # --- Minimal Release Notes ---
                $releaseNotes = "# CSVGenerator v$fileVersion (Test Build)`nBuild Date: $buildTime`nSHA256: $sha256`n`n## Changes`n$releaseNotesBody"
                $releaseNotesFilePath = Join-Path $stagingDir "release-notes.md"
                Set-Content -Path $releaseNotesFilePath -Value $releaseNotes
                Write-Output "INFO: Minimal release notes written."

                Write-Output "INFO: Setting GitHub Action outputs..."
                echo "version=$fileVersion" >> $env:GITHUB_OUTPUT
                echo "release_notes_path=$releaseNotesFilePath" >> $env:GITHUB_OUTPUT
                echo "assets_path=$stagingDir" >> $env:GITHUB_OUTPUT
                
                Write-Output "INFO: Script logic completed successfully. Attempting explicit exit 0."
                exit 0 
            } else {
                Write-Error "FATAL_ERROR: Main executable (CSVGenerator.exe) not found in $publishDir!"
                exit 1 
            }
        } catch {
            Write-Error "FATAL_ERROR in 'Prepare Release Assets and Metadata' step. Error: $($_.Exception.ToString())" 
            Write-Error "Failed at line: $($_.InvocationInfo.ScriptLineNumber)"
            exit 1 
        }
      shell: pwsh
      
    - name: Upload Build Artifact (for debugging/retention)
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: CSVGenerator-Build-Test-${{ steps.release-prep.outputs.version || github.run_number }}
        path: ${{ steps.publish-csvgenerator.outputs.publish__dir }}/ 
        if-no-files-found: warn 
        retention-days: 7
        
    - name: Create GitHub Release on 'test' branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/test' 
      uses: softprops/action-gh-release@v2
      with:
        name: Test Release - CSVGenerator v${{ steps.release-prep.outputs.version }}
        tag_name: test-v${{ steps.release-prep.outputs.version }}-${{ github.run_id }} 
        body_path: ${{ steps.release-prep.outputs.release_notes_path }}
        files: |
          ${{ steps.release-prep.outputs.assets_path }}/CSVGenerator.exe
          ${{ steps.release-prep.outputs.assets_path }}/CSVGenerator.exe.metadata.txt
        draft: false
        prerelease: true 
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} # Corrected to GITHUB_TOKEN from common secrets

    # Removed the final problematic debug step for now.
