name: Test Build CSVGenerator

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Common library
      uses: actions/checkout@v4
      with:
        repository: DarkPhilosophy/Common
        path: Common
        ref: test
        
    - name: Checkout CSVGenerator
      uses: actions/checkout@v4
      with:
        path: CSVGenerator
        ref: test
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Install .NET Framework 4.8 Developer Pack
      run: choco install netfx-4.8-devpack -y
      
    - name: Build with MSBuild for .NET Framework 4.8
      run: |
        cd CSVGenerator
        msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFramework=net48
