name: Test Build and Release CSVGenerator

on:
  push:
    branches: [ test ] 
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build-release: 
    runs-on: windows-latest
    
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout CSVGenerator (this repository)
      uses: actions/checkout@v4
      with:
        path: CSVGenerator
        fetch-depth: 0 

    - name: Checkout Common library
      uses: actions/checkout@v4
      with:
        repository: DarkPhilosophy/Common
        path: Common
        ref: test
        # token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
        
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y --no-progress
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Choco install failed for netfx-4.8-devpack"
          exit 1
        }

    - name: Temporarily update TargetFrameworks in project files for CI
      env:
        CI_WORKSPACE: ${{ github.workspace }} 
      run: |
        Write-Output "Script starting. Value of CI_WORKSPACE from step env: '$($env:CI_WORKSPACE)'"
        Write-Output "Script starting. Value of GITHUB_WORKSPACE from direct env access: '$($env:GITHUB_WORKSPACE)'"
        $baseWorkspacePath = $env:GITHUB_WORKSPACE
        if ([string]::IsNullOrWhiteSpace($baseWorkspacePath)) {
            Write-Warning "Direct $env:GITHUB_WORKSPACE was empty or null, trying $env:CI_WORKSPACE from step env."
            $baseWorkspacePath = $env:CI_WORKSPACE
        }
        if ([string]::IsNullOrWhiteSpace($baseWorkspacePath)) {
            Write-Error "Base workspace path is empty or null. Aborting."
            exit 1
        }
        Write-Output "Using base workspace path: '$baseWorkspacePath'"
        $csvGeneratorCheckoutPath = Join-Path $baseWorkspacePath "CSVGenerator" 
        $commonCheckoutPath = Join-Path $baseWorkspacePath "Common"          
        Write-Output "Calculated csvGeneratorCheckoutPath: '$csvGeneratorCheckoutPath'"
        Write-Output "Calculated commonCheckoutPath: '$commonCheckoutPath'"
        $projectRoots = @( $csvGeneratorCheckoutPath, $commonCheckoutPath )
        $tfmToReplace = 'net10.0-windows'; $tfmReplacement = 'net9.0-windows'
        $escapedTfmToReplace = [regex]::Escape($tfmToReplace)
        Write-Output "Project roots to scan: $($projectRoots -join ', ')"
        Write-Output "Searching for TargetFramework '$tfmToReplace' to replace with '$tfmReplacement'."
        foreach ($rootPath in $projectRoots) {
            if (Test-Path $rootPath) {
                Write-Output "Scanning directory: $rootPath"
                Get-ChildItem -Path $rootPath -Include *.csproj -Recurse | ForEach-Object {
                    $projectFile = $_.FullName; Write-Output "Processing project file: $projectFile"
                    $content = Get-Content $projectFile -Raw; $originalContent = $content; $wasModified = $false
                    if ($content.Contains($tfmToReplace)) {
                        Write-Output "Attempting simple string replace of '$tfmToReplace' in $projectFile"
                        $content = $content.Replace($tfmToReplace, $tfmReplacement)
                        if ($content -ne $originalContent) { Write-Output "Simple string replace successful."; $wasModified = $true }
                        else { Write-Output "Simple string replace did not alter content."}
                    }
                    if (-not $wasModified -and $content.Contains($tfmToReplace)) {
                        Write-Output "Simple replace failed/TFM still present. Trying regex."
                        $regexPatternForTargetFrameworks = "([<TargetFrameworks>].*?;?)\s*$($escapedTfmToReplace)\s*(;?.*?<\TargetFrameworks>)"
                        if ($content -match "<TargetFrameworks>.*$($escapedTfmToReplace).*</TargetFrameworks>") {
                            $tempContent = $content -replace $regexPatternForTargetFrameworks, ('$1' + $tfmReplacement + '$3')
                            if ($tempContent -ne $content) { $content = $tempContent; $wasModified = $true; Write-Output "Regex <TargetFrameworks> replace successful."}
                            else { Write-Output "Regex <TargetFrameworks> did not alter."}
                        }
                        if (-not $wasModified -and $content -match "<TargetFramework>$($escapedTfmToReplace)</TargetFramework>") {
                             $regexPatternForTargetFramework = "<TargetFramework>$($escapedTfmToReplace)</TargetFramework>"
                             $replacementForTf = "<TargetFramework>$($tfmReplacement)</TargetFramework>"
                             $tempContent = $content -replace $regexPatternForTargetFramework, $replacementForTf
                             if ($tempContent -ne $content) { $content = $tempContent; $wasModified = $true; Write-Output "Regex <TargetFramework> replace successful."}
                             else { Write-Output "Regex <TargetFramework> did not alter."}
                        }
                    }
                    if ($wasModified) { Set-Content -Path $projectFile -Value $content -Force -Encoding UTF8; Write-Output "Successfully saved $projectFile."}
                    else { Write-Output "No changes made to $projectFile."}
                }
            } else { Write-Warning "Path $rootPath does not exist."}
        }
      shell: pwsh
      
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-tfmfix-${{ hashFiles('**/csproj') }}-${{ github.run_id }} 
        restore-keys: |
          ${{ runner.os }}-nuget-tfmfix-${{ hashFiles('**/csproj') }}-
          ${{ runner.os }}-nuget-tfmfix-
          ${{ runner.os }}-nuget-
      
    - name: Build Common library for net48
      run: dotnet build (Join-Path $env:GITHUB_WORKSPACE "Common" "Common.csproj") -c Release -f net48

    - name: Publish CSVGenerator for net48
      id: publish-csvgenerator 
      run: |
        $publishDir = Join-Path $env:GITHUB_WORKSPACE "publish_output" "net48_win-x64"
        dotnet publish (Join-Path $env:GITHUB_WORKSPACE "CSVGenerator" "CSVGenerator.csproj") `
          -r win-x64 `
          -f net48 `
          -c Release `
          -o $publishDir
        Write-Output "CSVGenerator published to $publishDir"
        echo "publish_dir=$publishDir" >> $env:GITHUB_OUTPUT
        
    - name: Prepare Release Assets and Metadata
      id: release-prep 
      run: |
        $ErrorActionPreference = "Stop" 
        try {
            $publishDir = "${{ steps.publish-csvgenerator.outputs.publish_dir }}"
            Write-Output "INFO: Publish directory for asset prep: $publishDir"
            $stagingDir = Join-Path $env:GITHUB_WORKSPACE "release_staging"
            Write-Output "INFO: Attempting to create staging directory: $stagingDir"
            New-Item -ItemType Directory -Path $stagingDir -Force
            Write-Output "INFO: Staging directory ensured: $stagingDir"
            $exeFile = Get-ChildItem -Path $publishDir -Filter CSVGenerator.exe -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($exeFile) {
                Write-Output "INFO: Found executable: $($exeFile.FullName)"
                Copy-Item -Path $exeFile.FullName -Destination $stagingDir -Force
                $stagedExePath = Join-Path $stagingDir $exeFile.Name
                Write-Output "INFO: Copied EXE to staging path: $stagedExePath"
                Write-Output "INFO: Getting version info..."
                $versionInfo = (Get-Item $stagedExePath).VersionInfo
                $fileVersion = $versionInfo.FileVersion
                if ([string]::IsNullOrWhiteSpace($fileVersion)) {
                    Write-Warning "WARN: File version from EXE is empty, using '0.0.0.1' as fallback."
                    $fileVersion = "0.0.0.1" 
                }
                $productVersion = $versionInfo.ProductVersion
                Write-Output "INFO: FileVersion: $fileVersion, ProductVersion: $productVersion"
                Write-Output "INFO: Calculating SHA256 hash..."
                $sha256 = Get-FileHash -Path $stagedExePath -Algorithm SHA256 | Select-Object -ExpandProperty Hash
                Write-Output "INFO: SHA256: $sha256"
                $buildTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"
                Write-Output "INFO: BuildTime: $buildTime"
                $gitRepoPath = Join-Path $env:GITHUB_WORKSPACE "CSVGenerator"
                Write-Output "INFO: Attempting git operations in: $gitRepoPath"
                if (-not (Test-Path (Join-Path $gitRepoPath ".git"))) {
                    Write-Error "ERROR: Not a git repository at $gitRepoPath or .git folder not found."
                    exit 1 
                }
                Push-Location $gitRepoPath
                $commitHash = ""
                $rawCommitMessage = ""
                $latestTagName = ""
                try {
                    Write-Output "INFO: Getting commit hash..."
                    $commitHash = git rev-parse HEAD
                    Write-Output "INFO: CommitHash: $commitHash"
                    Write-Output "INFO: Getting commit message..."
                    $rawCommitMessage = (git log -1 --pretty=%B).Trim()
                    Write-Output "INFO: Raw CommitMessage line count: $($rawCommitMessage -split '(\r?\n)' | Measure-Object -Line | Select-Object -ExpandProperty Lines)"
                    Write-Output "INFO: Getting latest tag name (errors suppressed)..."
                    $latestTagName = $(git describe --tags --abbrev=0 2>$null)
                    if ([string]::IsNullOrWhiteSpace($latestTagName)) {
                        Write-Warning "WARN: No git tags found."
                        $latestTagName = $null 
                    } else { Write-Output "INFO: LatestTagName: $latestTagName" }
                } catch { Write-Error "ERROR: Failed during git operations. Error: $($_.Exception.Message)" }
                finally { Pop-Location; Write-Output "INFO: Popped location from git repo path." }

                # Prepare raw commit message for multi-line display in Markdown
                $formattedCommitMessage = ($rawCommitMessage -split '(\r?\n)' | ForEach-Object {
                    if ($_ -match '\S') { # If the line has non-whitespace content
                        $_.TrimEnd() + "  " # Add two spaces to the end of non-empty lines for Markdown hard break
                    } else {
                        $_ # Keep blank lines as they are (they'll create paragraph breaks)
                    }
                }) -join "`n" 
                Write-Output "INFO: Formatted commit message line count: $($formattedCommitMessage -split '`n' | Measure-Object -Line | Select-Object -ExpandProperty Lines)"
                
                Write-Output "INFO: Creating metadata content..."
                $metadataContent = "Product: CSVGenerator" + [Environment]::NewLine
                $metadataContent += "File: $($exeFile.Name)" + [Environment]::NewLine
                $metadataContent += "Version: $fileVersion" + [Environment]::NewLine
                $metadataContent += "ProductVersion: $productVersion" + [Environment]::NewLine
                $metadataContent += "Build Time: $buildTime" + [Environment]::NewLine
                $metadataContent += "Commit: $commitHash" + [Environment]::NewLine 
                $metadataContent += "Commit Message (raw):`n$rawCommitMessage" + [Environment]::NewLine 
                $metadataContent += "SHA256: $sha256"
                $metadataFilePath = Join-Path $stagingDir "$($exeFile.Name).metadata.txt"
                Write-Output "INFO: Writing metadata to: $metadataFilePath"
                Set-Content -Path $metadataFilePath -Value $metadataContent
                Write-Output "INFO: Metadata written."
                
                # Default release notes body (for single commit case)
                $defaultReleaseNotesBody = "- **Commit:** `$commitHash`" + [Environment]::NewLine
                $defaultReleaseNotesBody += "- **Message:**" + [Environment]::NewLine # Header for message
                $commitMessageBlock = ($formattedCommitMessage -split "`n" | ForEach-Object {
                    if ($_.Trim().Length -gt 0) { "  > " + $_.TrimEnd(" ") } # Trim our added spaces from the end
                    else { "" } # Skip fully blank lines from the source for the blockquote
                }) -join [Environment]::NewLine
                $defaultReleaseNotesBody += $commitMessageBlock.TrimEnd([Environment]::NewLine.ToCharArray())

                $releaseNotesBody = $defaultReleaseNotesBody # Assume single commit info first

                if ($latestTagName) { 
                    Write-Output "INFO: Getting commits since last tag ($latestTagName)..."
                    Push-Location $gitRepoPath
                    try {
                        $commitsSinceLastTag = git log "${latestTagName}..HEAD" --pretty=format:"- %s (`%h`)" --reverse | Where-Object { $_.Trim() }
                        if ($commitsSinceLastTag) {
                            Write-Output "INFO: Found commits since last tag."
                            $releaseNotesBody = "### Changes since ${latestTagName}" + [Environment]::NewLine + ($commitsSinceLastTag -join [Environment]::NewLine)
                        } else { 
                            Write-Output "INFO: No new commits found since last tag $latestTagName. Using single commit info (already set)."
                        }
                    } catch { 
                        Write-Error "ERROR: Failed getting commits since last tag. Error: $($_.Exception.Message)"
                        Write-Warning "WARN: Proceeding with single commit information for release notes."
                    }
                    finally { Pop-Location }
                } else {
                    Write-Output "INFO: No previous tags found. Using single commit information for release notes."
                }

                Write-Output "INFO: Creating release notes content..."
                $releaseNotes = "# CSVGenerator v$fileVersion (Test Build)" + [Environment]::NewLine
                $releaseNotes += "Build Date: $buildTime" + [Environment]::NewLine
                $releaseNotes += "SHA256: $sha256 ($($exeFile.Name))" + [Environment]::NewLine
                $releaseNotes += [Environment]::NewLine
                $releaseNotes += "## Details / Changes" + [Environment]::NewLine 
                $releaseNotes += $releaseNotesBody
                $releaseNotesFilePath = Join-Path $stagingDir "release-notes.md"
                Write-Output "INFO: Writing release notes to: $releaseNotesFilePath"
                Set-Content -Path $releaseNotesFilePath -Value $releaseNotes
                Write-Output "INFO: Release notes written."
                
                Write-Output "INFO: Setting GitHub Action outputs..."
                $outputVersion = "version=$fileVersion"; $outputReleaseNotesPath = "release_notes_path=$releaseNotesFilePath"; $outputAssetsPath = "assets_path=$stagingDir"
                Write-Output "INFO: Output to GITHUB_OUTPUT: $outputVersion"; echo $outputVersion >> $env:GITHUB_OUTPUT
                Write-Output "INFO: Output to GITHUB_OUTPUT: $outputReleaseNotesPath"; echo $outputReleaseNotesPath >> $env:GITHUB_OUTPUT
                Write-Output "INFO: Output to GITHUB_OUTPUT: $outputAssetsPath"; echo $outputAssetsPath >> $env:GITHUB_OUTPUT
                
                Write-Output "INFO: Release version (output check): $fileVersion"
                Write-Output "INFO: Staging directory for release assets (output check): $stagingDir"
                Write-Output "INFO: Script logic completed successfully. Attempting explicit exit 0."
                exit 0 
            } else { Write-Error "FATAL_ERROR: Main executable (CSVGenerator.exe) not found in $publishDir!"; exit 1 }
        } catch {
            Write-Error "FATAL_ERROR in 'Prepare Release Assets and Metadata' step. Error: $($_.Exception.ToString())" 
            Write-Error "Failed at line: $($_.InvocationInfo.ScriptLineNumber)"; exit 1 
        }
      shell: pwsh
      
    - name: Upload Build Artifact (for debugging/retention)
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: CSVGenerator-Build-Test-${{ steps.release-prep.outputs.version || github.run_number }}
        path: ${{ steps.publish-csvgenerator.outputs.publish_dir }}/ 
        if-no-files-found: warn 
        retention-days: 7
        
    - name: Create GitHub Release on 'test' branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/test' 
      uses: softprops/action-gh-release@v2
      with:
        name: Test Release - CSVGenerator v${{ steps.release-prep.outputs.version }}
        tag_name: test-v${{ steps.release-prep.outputs.version }}-${{ github.run_id }} 
        body_path: ${{ steps.release-prep.outputs.release_notes_path }}
        files: |
          ${{ steps.release-prep.outputs.assets_path }}/CSVGenerator.exe
          ${{ steps.release-prep.outputs.assets_path }}/CSVGenerator.exe.metadata.txt
        draft: false
        prerelease: true 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List directory structure (Post-Build Debugging)
      if: ${{ always() }} 
      run: |
        Write-Output "GITHUB_WORKSPACE (from github context): ${{ github.workspace }}"
        Write-Output "GITHUB_WORKSPACE (from env context): $env:GITHUB_WORKSPACE"
        Write-Output "Workspace root structure (using $env:GITHUB_WORKSPACE):"
        Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Depth 4 | Select-Object FullName, Length, LastWriteTime
        Write-Output "Contents of publish_output directory:"
        Get-ChildItem -Path (Join-Path $env:GITHUB_WORKSPACE "publish_output" "net48_win-x64") -Recurse -ErrorAction SilentlyContinue | Select-Object FullName, Length, LastWriteTime
        Write-Output "Contents of release_staging directory:"
        Get-ChildItem -Path (Join-Path $env:GITHUB_WORKSPACE "release_staging") -Recurse -ErrorAction SilentlyContinue | Select-Object FullName, Length, LastWriteTime
